### ISSUE TITLE
Could You Provide a demo or tutorial how you build this or how to use it

### ISSUE THREAD

**Issue by learnwithgabbar** [Yalantis/APIClient#1]

**Comment by learnwithgabbar** [comment]
Any update on this when you are going to release the tutorial and case study to use this component

**Comment by rnkyr** [comment]
Hi, @techmehra!
Currently, it's for internal use only. But we'll probably add some examples in the future

**Comment by rnkyr** [comment]
hey, @techmehra
we're not going to release any example/tutorials, but you can refer to updated Readme for more details on usage of the lib
