### ISSUE TITLE
empty response parsing

### ISSUE THREAD

**Issue by rnkyr** [Yalantis/APIClient#17]
in case there's an empty response APIClient couldn't parse it and sends errors:
`Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}`

need to handle the case in `JSONDeserializer`:

```
func deserialize(_ response: HTTPURLResponse, data: Data) throws -> AnyObject {
        do {
           ...
        } catch {
            if (error as NSError).code == 3840 { // empty response
                return .success(NSArray())
            }
               ...
        }
    }
```

**Comment by Vodolazkyi** [comment]
fixed in 2.3
