### ISSUE TITLE
dependency "APIClient" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by dharmendraiosdev** [Yalantis/APIClient#24]
It was working fine till Xcode 10.1 and Swift 4.2. Once I updated Xcode to 10.2.1 which support Swift 5.0, I started getting this error. I using Carthage manage dependencies.

# Your Environment

- Version of the component: 2.8
- Swift version: 5.0
- iOS version: 12.2.0
- Device: n/a
- Xcode version: 10.2.1
- If you use Cocoapods: n/a
- If you use Carthage: 0.33.0

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by rnkyr** [comment]
Hi @dharmendraiosdev,

yep, we haven't had Carthage support yet

I'll take a look at it shortly

**Comment by rnkyr** [comment]
hi @dharmendraiosdev,

just updated the repo. should be fixed by now
